imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: aplicacion.yml }
    - { resource: servicios.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id: ~ #set to null will use default session handler from php.ini
        name:                 TRACKERSID
        handler_id:           session.handler.native_file
        save_path:            %kernel.root_dir%/cache/sessions
       # gc_maxlifetime:       600 # 10 minutos (Si en 10 minutos el usuario no hace nada, lo manda al login)
        gc_divisor:           1
        gc_probability:       1
        cookie_httponly:      true
        cookie_lifetime:      600
        
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        global:
            app: "%app%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:
        - TrackerBundle
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
    assets:
        jquery_js:
            inputs:
                - %kernel.root_dir%/../web/bundles/tracker/js/jquery.min.js
                - %kernel.root_dir%/../web/bundles/tracker/js/jquery.maskedinput.min.js
                - %kernel.root_dir%/../web/bundles/tracker/js/jquery.form.js
                - %kernel.root_dir%/../web/bundles/tracker/js/jquery.uploadfile.min.js
        bootstrap_js:
            inputs:
                - %kernel.root_dir%/../web/bundles/tracker/js/bootstrap.min.js
                - %kernel.root_dir%/../web/bundles/tracker/js/bootstrap-datepicker.js
                - %kernel.root_dir%/../web/bundles/tracker/js/bootstrap-datepicker.es.js
                - %kernel.root_dir%/../web/bundles/tracker/js/alertify.min.js
                - %kernel.root_dir%/../web/bundles/tracker/js/bootstrap3-typeahead.min.js
                - %kernel.root_dir%/../web/bundles/tracker/js/bootstrap-multiselect.js
        bootstrap_css:
            inputs:
                - %kernel.root_dir%/../web/bundles/tracker/css/magic-bootstrap-custom.min.css
                - %kernel.root_dir%/../web/bundles/tracker/css/alertify.core.css
                - %kernel.root_dir%/../web/bundles/tracker/css/alertify.bootstrap.css
                - %kernel.root_dir%/../web/bundles/tracker/css/uploadfile.css
                - %kernel.root_dir%/../web/bundles/tracker/css/bootstrap-multiselect.css
        fontawesome_css:
            inputs:
                - %kernel.root_dir%/../web/bundles/tracker/css/font-awesome.css
        datepicker_css:
            inputs:
                - %kernel.root_dir%/../web/bundles/tracker/css/datepicker.css
        main_css:
            inputs:
                - %kernel.root_dir%/../web/bundles/tracker/css/main.css

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                mappings:
                    TrackerBundle: ~
                    SeguridadBundle: ~
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        alias: GedmoLoggable # this one is optional and will default to the name set for the mapping
                        is_bundle: false

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    #spool:     { type: memory }
    spool:
        type: file
        path: "%kernel.root_dir%/spool"

stof_doctrine_extensions:
    default_locale: es
    orm:
        default:
            loggable: true

white_october_tcpdf:
    class: 'Aleste\TrackerBundle\Util\Pdf'
    tcpdf:
        k_tcpdf_external_config: true
        k_path_images:  %kernel.root_dir%/../web/bundles/tracker/images/