parameters:
#    common.example.class: Aleste\CommonBundle\Example

services:
#    common.example:
#        class: %common.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

services:
    common_locale.locale_listener:
        class: Aleste\CommonBundle\Listener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }
